# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14502813d64dfb8e90b26c9be68e67c7"
name = "jigsaw-puzzle"
handle = "jigsaw-puzzle-1"
application_url = "https://estimated-metallic-properties-ontario.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jigsaw-craft.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://estimated-metallic-properties-ontario.trycloudflare.com/auth/callback",
  "https://estimated-metallic-properties-ontario.trycloudflare.com/auth/shopify/callback",
  "https://estimated-metallic-properties-ontario.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/gdpr/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/gdpr/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/gdpr/shop_redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
